name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pyqt5 numpy

      - name: Build with PyInstaller
        run: |
          pyinstaller chess_ui.py --noconsole --onefile --name BobaChess

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/BobaChess.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
